### ISSUE TITLE
[Sugestão] Botar o youtube como opção de rede social

### ISSUE THREAD

**Issue by kaykemigon** [bolodissenoura/pixmeacoffee#12]
Incluir o YouTube como opção de rede social no site é uma escolha estratégica, especialmente considerando que a maioria dos usuários será composta por streamers. Eu fiz uma alteração, mas não da pra criar request pull.

**Comment by bolodissenoura** [comment]
Vou adicionar ! 
Vou colocar uma feature essa semana que da pra pessoa colocar inumeros links, de diversas coisas.
Bom vc ter falado sobre stream, teremos uma parceria em breve com a alertpix.live
